/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mumu_glmodel_render_Renderer */

#ifndef _Included_com_mumu_glmodel_render_Renderer
#define _Included_com_mumu_glmodel_render_Renderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mumu_glmodel_render_Renderer
 * Method:    createProgram
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mumu_glmodel_render_Renderer_createProgram
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_mumu_glmodel_render_Renderer
 * Method:    genRenderParams
 * Signature: (Lcom/mumu/glmodel/model/ModelStruct;)V
 */
JNIEXPORT void JNICALL Java_com_mumu_glmodel_render_Renderer_genRenderParams
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mumu_glmodel_render_Renderer
 * Method:    render
 * Signature: (IZIIIIFFFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_mumu_glmodel_render_Renderer_render
  (JNIEnv *, jobject, jint, jboolean, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mumu_glmodel_render_Renderer
 * Method:    loadBitmapTextrue
 * Signature: (Landroid/graphics/Bitmap;I)I
 */
JNIEXPORT jint JNICALL Java_com_mumu_glmodel_render_Renderer_loadBitmapTextrue
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_mumu_glmodel_render_Renderer
 * Method:    resizeWindow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mumu_glmodel_render_Renderer_resizeWindow
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mumu_glmodel_render_Renderer
 * Method:    rotateModel
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_mumu_glmodel_render_Renderer_rotateModel
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mumu_glmodel_render_Renderer
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mumu_glmodel_render_Renderer_clean
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
