/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mumu_glmodel_model_ModelLoader */

#ifndef _Included_com_mumu_glmodel_model_ModelLoader
#define _Included_com_mumu_glmodel_model_ModelLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mumu_glmodel_model_ModelLoader
 * Method:    parseModelCoordinate
 * Signature: (Ljava/lang/String;)Lcom/mumu/glmodel/model/ModelCoordinate;
 */
JNIEXPORT jobject JNICALL Java_com_mumu_glmodel_model_ModelLoader_parseModelCoordinate
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mumu_glmodel_model_ModelLoader
 * Method:    parseModelMtl
 * Signature: (Ljava/lang/String;)Lcom/mumu/glmodel/model/ModelMtl;
 */
JNIEXPORT jobject JNICALL Java_com_mumu_glmodel_model_ModelLoader_parseModelMtl
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
